General:
  KAFKA_BROKER_URL: kafka:9093
  KAFKA_CONSUMER_TIMEOUT_MS: 120000
  KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081

1p_count_up:
  OUT_TOPIC:
    count: ./schema/count.avsc

2c_print:
  IN_TOPIC:
    - count
    - multiples
  IN_GROUP: count
