0_p_schema_init:
  OUT_TOPIC:
    AB_apply_on_cpps: ./schema/new_x.avsc
    AB_application_results: ./schema/application_result.avsc
    AB_simulation_results: ./schema/simulation_result.avsc
    DB_features: ./schema/CPPSFeatures.avsc
    AB_model_data: ./schema/model.avsc
    AB_simulation_model: ./schema/simulation_model.avsc
    AB_simulation_model_data: ./schema/simulation_model.avsc
