1_pc_model_learning_rf:
  MODEL_ALGORITHM: Random Forest
  MODEL_PARAMETERS:
    n_estimators: 3
  IN_TOPIC:
    - DB_features
    - AB_test_function
  IN_GROUP: RF
  OUT_TOPIC:
    AB_model_data: ./schema/model.avsc
    AB_simulation_model_data: ./schema/simulation_model.avsc
  API_URL: http://api-knowledge-service.default:80
