2_pc_optimizer_lbfgsb:
  OPTIMIZER_NAME: L-BFGS-B
  OPTIMIZATION_PARAMETERS:
    maxfun: 40
  IN_TOPIC:
    - DB_raw_data
    - AB_test_function
  IN_GROUP: BFGS
  OUT_TOPIC:
    AB_apply_on_cpps: ./schema/new_x.avsc
    AB_application_results: ./schema/application_result.avsc 
    AB_simulation_results: ./schema/simulation_result.avsc
  API_URL: http://5_API_Knowledge:8000
