4_c_reporting:
  IN_TOPIC:
    - AB_monitoring
    - AB_application_results
    - AB_simulation_results
    - AB_cluster_monitoring
  IN_GROUP: reporting
  OUT_TOPIC:
    AB_plot_data: ./schema/plot.avsc
  PLOT_TOPIC:
    AB_model_evaluation: plot_data_multi
    AB_monitoring: plot_monitoring
    AB_application_results: plot_model_application
  API_OUT:
    AB_monitoring: forward_topic
    AB_application_results: forward_topic
    AB_simulation_results: forward_topic
    AB_cluster_monitoring: forward_topic
  API_URL: http://api-topic-data-service.default:80
  API_ENDPOINT: /topic/
