version: '2'

services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"

  kafka:
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    expose:
    - "9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      JVM_OPTS: "-Xms32M -Xmx64M"

  karapace-registry:
    container_name: schema-registry
    hostname: schema-registry
    image: koarch/karapace-registry:2.0.1-amd64
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KARAPACE_REGISTRY_ADVERTISED_HOSTNAME: schema-registry
      KARAPACE_REGISTRY_BOOTSTRAP_URI: kafka:9093
      KARAPACE_REGISTRY_PORT: 8081
      KARAPACE_REGISTRY_HOST: 0.0.0.0
      KARAPACE_REGISTRY_CLIENT_ID: karapace
      KARAPACE_REGISTRY_GROUP_ID: karapace-registry
      KARAPACE_REGISTRY_MASTER_ELIGIBITY: "true"
      KARAPACE_REGISTRY_TOPIC_NAME: _schemas

networks:
  default:
    external:
      name: caai
