# Default values for kafka-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Lists the secrets you need to use to pull kafka-operator image from a private registry.
imagePullSecrets: []
  # - private-registry-key

operator:
  annotations: {}
  image:
    repository: banzaicloud/kafka-operator
    tag: v0.11.2
    pullPolicy: IfNotPresent
  vaultAddress: ""
  # vaultSecret containing a `ca.crt` key with the Vault CA Certificate
  vaultSecret: ""
  # set of namespaces where the operator watches resources
  namespaces: ""
  verboseLogging: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

webhook:
  enabled: true
  certs:
    generate: true
    secret: "kafka-operator-serving-cert"

certManager:
  namespace: "cert-manager"
  enabled: false

alertManager:
  enable: true

prometheusMetrics:
  enabled: true
  authProxy:
    enabled: true
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.4.0
      pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: true

nodeSelector: {}

tolerations: []

affinity: {}
