---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cognition
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cognition
rules:
- apiGroups: ["", "batch"]
  resources: ["jobs", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-admin
subjects:
- kind: ServiceAccount
  name: cognition
  namespace: default
roleRef:
  kind: ClusterRole
  name: cognition
  apiGroup: rbac.authorization.k8s.io
