apiVersion: v1
kind: Pod
metadata:
  name: cognition
spec:
  containers:
    - name: cognition
      image: koarch/cognition_create_jobs_example:latest
  restartPolicy: Never
  serviceAccountName: cognition
---
