apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "kafka-operator.fullname" . }}-operator"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
    app.kubernetes.io/name: {{ include "kafka-operator.name" . }}
    helm.sh/chart: {{ include "kafka-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
      app.kubernetes.io/name: {{ include "kafka-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: operator
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/operator-validating-webhook.yaml") . | sha256sum }}
        {{- with .Values.operator.annotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
        app.kubernetes.io/name: {{ include "kafka-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: operator
        app: prometheus
        component: alertmanager
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ include "kafka-operator.fullname" . }}-operator
      {{- end }}
      volumes:
      {{- if .Values.webhook.enabled }}
        - name: serving-cert
          secret:
            secretName: {{ .Values.webhook.certs.secret }}
      {{- end }}
      {{- if .Values.operator.vaultSecret }}
        - name: {{ .Values.operator.vaultSecret }}
          secret:
            secretName: {{ .Values.operator.vaultSecret }}
      {{- end }}
      containers:
      {{- if and .Values.prometheusMetrics.enabled .Values.prometheusMetrics.authProxy.enabled }}
        - name: kube-rbac-proxy
          image: "{{ .Values.prometheusMetrics.authProxy.image.repository }}:{{ .Values.prometheusMetrics.authProxy.image.tag }}"
          imagePullPolicy: {{ .Values.prometheusMetrics.authProxy.image.pullPolicy }}
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
      {{- end }}
        - command:
            - /manager
          args:
            - --enable-leader-election
            - --cert-manager-namespace={{ .Values.certManager.namespace }}
            - --cert-manager-enabled={{ .Values.certManager.enabled }}
          {{- if not .Values.webhook.enabled }}
            - --disable-webhooks
          {{- end }}
          {{- if .Values.operator.namespaces }}
            - --namespaces={{ .Values.operator.namespaces }}
          {{- end }}
          {{- if .Values.operator.verboseLogging }}
            - --verbose
          {{- end }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.operator.vaultAddress }}
            - name: VAULT_ADDR
              value: {{ .Values.operator.vaultAddress }}
          {{- end }}
          {{- if .Values.operator.vaultSecret }}
            - name: VAULT_CACERT
              value: /etc/vault/certs/ca.crt
          {{- end }}
          ports:
          {{- if .Values.webhook.enabled }}
            - containerPort: 443
              name: webhook-server
              protocol: TCP
          {{- end }}
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 9001
              name: alerts
              protocol: TCP
          volumeMounts:
          {{- if .Values.webhook.enabled }}
            - mountPath: /etc/webhook/certs
              name: serving-cert
              readOnly: true
          {{- end }}
          {{- if .Values.operator.vaultSecret }}
            - mountPath: /etc/vault/certs
              name: {{ .Values.operator.vaultSecret }}
              readOnly: true
          {{- end }}
          resources:
{{ toYaml .Values.operator.resources | nindent 12 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 10
