FROM koarch/confluent_kafka_python:1.6.0

# standard python libs
COPY ./configurations/requirements.txt /
RUN pip install -r requirements.txt

COPY . /src
WORKDIR /src

CMD ["python", "-u", "L4_C_Reporting.py"]
