FROM python:3.7-slim-buster

COPY ./configurations/requirements_API.txt /
RUN pip install -r requirements_API.txt

COPY ./L0_API_CPPS_Controller.py /src/
WORKDIR /src

CMD ["uvicorn", "L0_API_CPPS_Controller:CPPS_Controller", "--host", "0.0.0.0", "--log-level", "warning"]
