FROM koarch/confluent_kafka_python_r:1.6.0

# standard python libs
COPY ./configurations/requirements.txt /
RUN pip install -r requirements.txt

# install r packages
COPY ./configurations/requirements.R /
RUN Rscript requirements.R

COPY . /src
WORKDIR /src

CMD ["python", "-u", "L1_PC_Model_Learning.py"]
