FROM python:3.7-slim-buster

# standard python libs
COPY ./configurations/requirements.txt /
RUN pip install -r requirements.txt

COPY . /src
WORKDIR /src

CMD ["uvicorn", "L5_API_HMI:results_api", "--host", "0.0.0.0", "--log-level", "warning"]
