FROM python:3.7-slim-buster

# standard python libs
COPY ./configurations/requirements.txt /
RUN pip install -r requirements.txt

COPY . /src
WORKDIR /src

CMD ["python", "-u", "L2_PC_Model_appl_opt.py"]
