FROM python:3.7-slim-buster

COPY ./configurations/requirements_API_Knowledge.txt /
RUN pip install -r requirements_API_Knowledge.txt

COPY ./L5_API_Knowledge.py /src/
COPY ./data/knowledge.yaml /src/
WORKDIR /src

CMD ["uvicorn", "L5_API_Knowledge:knowledgebase", "--host", "0.0.0.0", "--log-level", "warning"]
