version: '2'

services:
  1p_count_up:
    container_name: 1p_count_up
    build:
      context: ./src
      dockerfile: Dockerfile_1p_count_up
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 1p_count_up

  1p_multiples:
    container_name: 1p_multiples
    build:
      context: ./src
      dockerfile: Dockerfile_1p_multiples
      
networks:
  default:
    external:
      name: caai
