FROM node:12

COPY /Use_Cases/VPS_Popcorn_Production/Kubernetes/src/configurations/package*.json ./
RUN npm install

RUN apt-get update
RUN apt-get install -y python-pip
RUN pip install plotly==4.10.0

COPY /Use_Cases/VPS_Popcorn_Production/Kubernetes/src/ /src
WORKDIR /src

CMD ["node", "L4_plotServer.js"]
