version: '2'

services:
  0_api_cpps_controller:
    container_name: 0_API_CPPS_Controller
    hostname: 0_API_CPPS_Controller
    build:
      context: ./src
      dockerfile: Dockerfile_0_API_CPPS_Controller
    expose:
    - "8000"
    ports:
    - "8000:8000"

  0_pc_cpps:
    container_name: 0_PC_CPPS
    build:
      context: ./src
      dockerfile: Dockerfile_0_PC_CPPS
    environment:
      config_path: ./configurations/config.yml
      config_section: General, Initial_Design, Objective_Function, 0_pc_cpps
    depends_on:
      - 3_pc_evaluation

  1_pc_monitoring:
    container_name: 1_PC_Monitoring
    build:
      context: ./src
      dockerfile: Dockerfile_1_PC_Monitoring
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 1_pc_monitoring

  1_pc_model_learning_rf:
    container_name: 1_PC_Model_Learning_RF
    build:
      context: ./src
      dockerfile: Dockerfile_1_PC_Model_Learning
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 1_pc_model_learning_rf
    depends_on:
      - 5_api_knowledge

  1_pc_model_learning_kriging:
    container_name: 1_PC_Model_Learning_Kriging
    build:
      context: ./src
      dockerfile: Dockerfile_1_PC_Model_Learning
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 1_pc_model_learning_kriging
    depends_on:
      - 5_api_knowledge

  2_pc_model_appl_opt:
    container_name: 2_PC_Model_appl_opt
    build:
      context: ./src
      dockerfile: Dockerfile_2_PC_Model_appl_opt
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 2_pc_model_appl_opt

  2_pc_optimizer:
    container_name: 2_PC_Optimizer
    build:
      context: ./src
      dockerfile: Dockerfile_2_PC_Optimizer
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 2_pc_optimizer

  3_pc_evaluation:
    container_name: 3_PC_Evaluation
    build:
      context: ./src
      dockerfile: Dockerfile_3_PC_Evaluation
    environment:
      config_path: ./configurations/config.yml
      config_section: General, Initial_Design, Objective_Function, 3_pc_evaluation
    depends_on:
      - 4_pc_adaption

  3_pc_simulation:
    container_name: 3_PC_Simulation
    build:
      context: ./src
      dockerfile: Dockerfile_3_PC_Simulation
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 3_pc_simulation

  4_pc_adaption:
    container_name: 4_PC_Adaption
    build:
      context: ./src
      dockerfile: Dockerfile_4_PC_Adaption
    environment:
        config_path: ./configurations/config.yml
        config_section: General, 4_pc_adaption
    depends_on:
      - 0_api_cpps_controller

  # 4_plot_data:
  #   container_name: 4_Plot_Data
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile_4_Plot_Data
  #   environment:
  #     config_path: ./configurations/config.yml
  #     config_section: 4_plot_data
  #   expose:
  #   - "8000"
  #   ports:
    # - "8003:8000"

  # 4_c_reporting:
  #   container_name: 4_C_Reporting
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile_4_C_Reporting
  #   environment:
  #     config_path: ./configurations/config.yml
  #     config_section: General, 4_c_reporting
  #   depends_on:
  #     - 5_api_hmi

  # 5_api_hmi:
  #   container_name: 5_API_HMI
  #   hostname: 5_API_HMI
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile_5_API_HMI
  #   environment:
  #     config_path: ./configurations/config.yml
  #     config_section: 4_c_reporting
  #   expose:
  #   - "8000"
  #   ports:
  #   - "8001:8000"

  5_api_knowledge:
    container_name: 5_API_Knowledge
    hostname: 5_API_Knowledge
    build:
      context: ./src
      dockerfile: Dockerfile_5_API_Knowledge
    expose:
    - "8000"
    ports:
    - "8002:8000"

networks:
  default:
    external:
      name: caai
