version: '2'

services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    environment:
      ZOOKEEPER_SESSION_TIMEOUT_MS: 120000

  kafka:
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    expose:
    - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # ZOOKEEPER_CONNECTION_TIMEOUT_MS: 120000
      # ZOOKEEPER_SESSION_TIMEOUT_MS: 120000
      # KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 120000
      # KAFKA_SESSION_TIMEOUT_MS: 120000
      # KAFKA_REBALANCE_MAX_RETRIES: 5
      # KAFAK_REBALANCE_BACKOFF_MS: 10000
      # KAFKA_REQUEST_TIMEOUT_MS: 50000
      # KAFKA_CREATE_TOPICS: "DB_raw_data:1:1,AB_monitoring:1:1,AB_model_data:1:1,AB_model_application:1:1,AB_model_evaluation:1:1"

networks:
  default:
    external:
      name: caai
