apiVersion: v1
kind: Deployment
metadata:
  name: 0-api-cpps-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  template:
    containers:
      - name: 0-api-cpps-controller
        image: koarch/vps_0_api_cpps_controller:0.1-amd64
---
# TODO API Service
---
apiVersion: v1
kind: Deployment
metadata:
  name: 0-pc-cpps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  containers:
    - name: 0-pc-cpps
      image: koarch/vps_0_pc_cpps:0.1-amd64
      env:
        - name: config_path
          value: "/etc/config/"
      volumeMounts:
        - name: general
          mountPath: /etc/config/general.yml
          subPath: general.yml
        - name: initial-design
          mountPath: /etc/config/initial-design.yml
          subPath: initial-design.yml
        - name: objective-function
          mountPath: /etc/config/objective-function.yml
          subPath: objective-function.yml
        - name: 0-pc-cpps
          mountPath: /etc/config/0-pc-cpps.yml
          subPath: 0-pc-cpps.yml
  volumes:
    - name: general
      configMap:
        name: general
        items:
          - key: general.yml
            path: general.yml
    - name: initial-design
      configMap:
        name: initial-design
        items:
          - key: initial-design.yml
            path: initial-design.yml
    - name: objective-function
      configMap:
        name: objective-function
        items:
          - key: objective-function.yml
            path: objective-function.yml
    - name: 0-pc-cpps
      configMap:
        name: 0-pc-cpps
        items:
          - key: 0-pc-cpps.yml
            path: 0-pc-cpps.yml

---
apiVersion: v1
kind: Deployment
metadata:
  name: 1-pc-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  containers:
    - name: 1-pc-monitoring
      image: koarch/vps_1_pc_monitoring:0.1-amd64
      env:
        - name: config_path
          value: "/etc/config/"
      volumeMounts:
        - name: general
          mountPath: /etc/config/general.yml
          subPath: general.yml
        - name: 1-pc-monitoring
          mountPath: /etc/config/1-pc-monitoring.yml
          subPath: 1-pc-monitoring.yml
  volumes:
    - name: general
      configMap:
        name: general
        items:
          - key: general.yml
            path: general.yml
    - name: 1-pc-monitoring
      configMap:
        name: 1-pc-monitoring
        items:
          - key: 1-pc-monitoring.yml
            path: 1-pc-monitoring.yml

---
apiVersion: v1
kind: Deployment
metadata:
  name: 3-pc-evaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  containers:
    - name: 3-pc-evaluation
      image: koarch/vps_3_pc_evaluation:0.1-amd64
      env:
        - name: config_path
          value: "/etc/config/"
      volumeMounts:
        - name: general
          mountPath: /etc/config/general.yml
          subPath: general.yml
        - name: initial-design
          mountPath: /etc/config/initial-design.yml
          subPath: initial-design.yml
        - name: objective-function
          mountPath: /etc/config/objective-function.yml
          subPath: objective-function.yml
        - name: 3-pc-evaluation
          mountPath: /etc/config/3-pc-evaluation.yml
          subPath: 3-pc-evaluation.yml
  volumes:
    - name: general
      configMap:
        name: general
        items:
          - key: general.yml
            path: general.yml
    - name: initial-design
      configMap:
        name: initial-design
        items:
          - key: initial-design.yml
            path: initial-design.yml
    - name: objective-function
      configMap:
        name: objective-function
        items:
          - key: objective-function.yml
            path: objective-function.yml
    - name: 3-pc-evaluation
      configMap:
        name: 3-pc-evaluation
        items:
          - key: 3-pc-evaluation.yml
            path: 3-pc-evaluation.yml

---
apiVersion: v1
kind: Deployment
metadata:
  name: 3-pc-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  containers:
    - name: 3-pc-simulation
      image: koarch/vps_3_pc_simulation:0.1-amd64
      env:
        - name: config_path
          value: "/etc/config/"
      volumeMounts:
        - name: general
          mountPath: /etc/config/general.yml
          subPath: general.yml
        - name: 3-pc-simulation
          mountPath: /etc/config/3-pc-simulation.yml
          subPath: 3-pc-simulation.yml
  volumes:
    - name: general
      configMap:
        name: general
        items:
          - key: general.yml
            path: general.yml
    - name: 3-pc-simulation
      configMap:
        name: 3-pc-simulation
        items:
          - key: 3-pc-simulation.yml
            path: 3-pc-simulation.yml

---
apiVersion: v1
kind: Deployment
metadata:
  name: 4-pc-adaption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  containers:
    - name: 4-pc-adaption
      image: koarch/vps_4_pc_adaption:0.1-amd64
      env:
        - name: config_path
          value: "/etc/config/"
      volumeMounts:
        - name: general
          mountPath: /etc/config/general.yml
          subPath: general.yml
        - name: 4-pc-adaption
          mountPath: /etc/config/4-pc-adaption.yml
          subPath: 4-pc-adaption.yml
  volumes:
    - name: general
      configMap:
        name: general
        items:
          - key: general.yml
            path: general.yml
    - name: 4-pc-adaption
      configMap:
        name: 4-pc-adaption
        items:
          - key: 4-pc-adaption.yml
            path: 4-pc-adaption.yml

---
apiVersion: v1
kind: Deployment
metadata:
  name: 5-api-knowledge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-use-case
  containers:
    - name: 5-api-knowledge
      image: koarch/vps_5_api_knowledge:0.1-amd64

---
# TODO API Service
