apiVersion: v1
kind: Pod
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  containers:
    - name: kafdrop
      image: koarch/kafdop:0.1-amd64
      ports:
        - containerPort: 9000
      env:
        - name: KAFKA_BROKERCONNECT
          value: "kafka-all-broker:29092"
        - name: SCHEMAREGISTRY_CONNECT
          value: "http://karapace-registry-service:80"
        - name: JVM_OPTS
          value: "-Xms32M -Xmx64M"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
spec:
  selector:
    app: kafdrop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      name: kafdrop
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafdrop-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /kafdrop
            pathType: Exact
            backend:
              service:
                name: kafdrop-service
                port:
                  number: 80
